format = """
[](#f38ba8)\
$username\
[](fg:#f38ba8 bg:#a6e3a1)\
$directory\
[](fg:#a6e3a1) \
\
"""

right_format = """$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = true
continuation_prompt = '▶▶ '

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#11111b bg:#f38ba8"
style_root = "fg:#11111b bg:#f38ba8"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true

[directory]
style = "fg:#11111b bg:#a6e3a1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[cmd_duration]
min_time = 0
show_milliseconds = true
style = "fg:#f9e2af"
format = "[ $duration ]($style)"


[c]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#F9C747F"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#90BE6D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#90BE6D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "󰌠"
style = "bg:#4D908E"
format = '[ $symbol ($version)(\($virtualenv\) )]($style)'

[lua]
symbol = "󰢱"
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "󱘗"
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#4D908E"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#277DA1"
#format = '[ ♥ $time ]($style)'
format = '[ $time ]($style)'
